### ISSUE TITLE
It might be an idea to move this project to @fsprojects.

### ISSUE THREAD

**Issue by albertjan** [simonhdickson/Fancy#10]
What do you think?

**Comment by simonhdickson** [comment]
I don't know if this is an appropriate repo for fsproject.

**Comment by albertjan** [comment]
Me neither, we are using it in production these days :smile:, and I think it's the best solution to use nancy from fsharp. 

Maybe it's a better idea to see if it can be moved to the @nancyfx guys see if we can convince them to advocate this as the way to use nancy from f#?
