### ISSUE TITLE
Update Nuget Package

### ISSUE THREAD

**Issue by TheAngryByrd** [simonhdickson/Fancy#11]
Could you please update the nuget package? Thank you! :guitar: :beers: :cake: :sparkles:

**Comment by albertjan** [comment]
@simonhdickson an actual user! :smile: quick quick.

**Comment by albertjan** [comment]
@TheAngryByrd https://ci.appveyor.com/nuget/fancy-bac27v45vsu7 you can get a prerelease version from there. It's my own build. @simonhdickson's build on appveyor will also have a source like that but I don't know the url.

@simonhdickson lets get this fixed! :smile: I'm willing to spend time the on it.
